### ISSUE TITLE
Request nRF54L15, nRF54L10, and nRF54L05  Wireless SoCs

### ISSUE THREAD

**Issue by huunhanspkt03** [huunghiaspkt/FIC_OAL#44]
https://docs-be.nordicsemi.com/bundle/ps_nrf54L15/page/pdf/nRF54L15_nRF54L10_nRF54L05_Datasheet_v0.7.pdf

**Comment by huunhanspkt03** [comment]
ID commit : 4e118ec

**Comment by huunghiaspkt** [comment]
Symbol Name: SoC_nRF54L15QF
